{% set name = "xee" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xee-{{ version }}.tar.gz
  sha256: 53c06649d2631a47e39cd68057dacdc045b8f79b784224b2d9154d40c90901c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - affine
    - earthengine-api >=0.1.374
    - pyproj
    - xarray

test:
  imports:
    - xee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xee
  summary: A Google Earth Engine extension for Xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - giswqs
