{% set name = "xee" %}
{% set version = "0.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xee-{{ version }}.tar.gz
  sha256: 946985906de81bf352905247a8f337132e8e65fd0b4d014c35dfa39abb694964

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - affine
    - earthengine-api >=0.1.374
    - pyproj
    - xarray
    - dask

test:
  imports:
    - xee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/xee
  summary: A Google Earth Engine extension for Xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - giswqs
