{% set name = "xee" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xee-{{ version }}.tar.gz
  sha256: 17eeffa5639402612ef75e88d25d88ae1909c2e0ca4a53ae2419ae9c42c20692

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - affine
    - earthengine-api >=0.1.374
    - pyproj
    - xarray
    - dask

test:
  imports:
    - xee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xee
  summary: A Google Earth Engine extension for Xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - giswqs
