{% set name = "xee" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xee-{{ version }}.tar.gz
  sha256: 75ecf23cd9a0261c676457d544498152877a58a69e6922771089fbd7a328ac5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - affine
    - earthengine-api >=0.1.374
    - gcloud
    - pyproj
    - xarray

test:
  imports:
    - xee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/xee
  summary: A Google Earth Engine extension for Xarray.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - giswqs
